<?php
    namespace Model;
    use Model\Util;
    class SAP extends Util {
        protected function setPurGroup($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = $item->ekgrp;
                $sqls = "INSERT INTO pur_grps ( objky,
                                                objnm,
                                                ekgrp, 
                                                ektel,
                                                email,
                                                phone,
                                                extno )
                                      values  ( :objky,
                                                :objnm,
                                                :ekgrp,
                                                :ektel,
                                                :email,
                                                :phone,
                                                :extno ) 
                            ON DUPLICATE KEY UPDATE 
                                ekgrp  = values(ekgrp),
                                ektel  = values(ektel),
                                email  = values(email),
                                phone  = values(phone),
                                extno  = values(extno),
                                cngdt  = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->eknam,
                                        $item->ekgrp,
                                        $item->ektel,
                                        $item->smtp_addr,
                                        $item->tel_number,
                                        $item->tel_extens));
            }
            $conn = null;
        }
        protected function setSupplier($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = str_pad($item->lifnr, 10, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO supplier ( objky, 
                                                lifnr,
                                                objnm,
                                                name2,
                                                name4,
                                                land1,
                                                ort01,
                                                ort02,
                                                pstlz,
                                                ktokk,
                                                kunnr,
                                                spras,
                                                regio ) 
                                      values  (:objky,
                                               :lifnr,
                                               :objnm,
                                               :name2,
                                               :name4,
                                               :land1,
                                               :ort01,
                                               :ort02,
                                               :pstlz,
                                               :ktokk,
                                               :kunnr,
                                               :spras,
                                               :regio ) 
                            ON DUPLICATE KEY UPDATE 
                                    lifnr = values(lifnr),
                                    objnm = values(objnm),
                                    name2 = values(name2),
                                    name4 = values(name4),
                                    land1 = values(land1),
                                    ort01 = values(ort01),
                                    ort02 = values(ort02),
                                    pstlz = values(pstlz),
                                    ktokk = values(ktokk),
                                    kunnr = values(kunnr),
                                    spras = values(spras),
                                    regio = values(regio),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->lifnr,
                                        $item->name1,
                                        $item->name2,
                                        $item->name4,
                                        $item->land1,
                                        $item->ort01,
                                        $item->ort02,
                                        $item->pstlz,
                                        $item->ktokk,
                                        $item->kunnr,
                                        $item->spras,
                                        $item->regio));
            }
            $conn = null;
        }
        protected function setPoCond($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->ebelp = $item->kposn;
                $item->objky = "{$item->ebeln}".str_pad($item->ebelp, 5, "0", STR_PAD_LEFT)."{$item->kschl}";
                $sqls = "INSERT INTO zpoc     ( objky,
                                                knumv,
                                                kposn,
                                                stunr,
                                                zaehk, 
                                                ebeln, 
                                                ebelp, 
                                                kschl, 
                                                kbetr, 
                                                waers, 
                                                kpein, 
                                                kmein, 
                                                lifnr,
                                                name1 ) 
                                      values  ( :objky,
                                                :knumv,
                                                :kposn,
                                                :stunr,
                                                :zaehk,
                                                :ebeln,
                                                :ebelp,
                                                :kschl,
                                                :kbetr,
                                                :waers,
                                                :kpein,
                                                :kmein,
                                                :lifnr,
                                                :name1) 
                            ON DUPLICATE KEY UPDATE 
                                    objky = values(objky),
                                    knumv = values(knumv),
                                    kposn = values(kposn),
                                    stunr = values(stunr),
                                    zaehk = values(zaehk),
                                    ebeln = values(ebeln),
                                    ebelp = values(ebelp),
                                    kschl = values(kschl),
                                    kbetr = values(kbetr),
                                    waers = values(waers),
                                    kpein = values(kpein),
                                    kmein = values(kmein),
                                    lifnr = values(lifnr),
                                    name1 = values(name1),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->knumv,
                                        $item->kposn,
                                        $item->stunr,
                                        $item->zaehk,
                                        $item->ebeln,
                                        $item->ebelp,
                                        $item->kschl,
                                        $item->kbetr,
                                        $item->waers,
                                        $item->kpein,
                                        $item->kmein,
                                        $item->lifnr,
                                        $item->name1  ));
            }
            $conn = null;
        }
        protected function setPOItem($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->ebeln}".str_pad($item->ebelp, 5, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zpoi     ( objky, 
                                                ebeln, 
                                                ebelp, 
                                                loekz, 
                                                aedat, 
                                                matnr, 
                                                ematn, 
                                                txz01, 
                                                bukrs, 
                                                werks, 
                                                lgort, 
                                                matkl, 
                                                ktmng, 
                                                menge, 
                                                meins,
                                                uebto,
                                                netpr, 
                                                peinh, 
                                                netwr,
                                                brtwr,
                                                pstyp, 
                                                knttp, 
                                                lmein, 
                                                bstyp, 
                                                bsart, 
                                                statu, 
                                                lifnr, 
                                                name1, 
                                                zterm, 
                                                ekorg, 
                                                ekgrp, 
                                                waers, 
                                                bedat, 
                                                kdatb, 
                                                kdate, 
                                                elikz, 
                                                emlif, 
                                                lblkz, 
                                                frgke,
                                                xchar) 
                                      values  ( :objky,
                                                :ebeln,
                                                :ebelp,
                                                :loekz,
                                                :aedat,
                                                :matnr,
                                                :ematn,
                                                :txz01,
                                                :bukrs,
                                                :werks,
                                                :lgort,
                                                :matkl,
                                                :ktmng,
                                                :menge,
                                                :meins,
                                                :uebto,
                                                :netpr,
                                                :peinh,
                                                :netwr,
                                                :brtwr,
                                                :pstyp,
                                                :knttp,
                                                :lmein,
                                                :bstyp,
                                                :bsart,
                                                :statu,
                                                :lifnr,
                                                :name1,
                                                :zterm,
                                                :ekorg,
                                                :ekgrp,
                                                :waers,
                                                :bedat,
                                                :kdatb,
                                                :kdate,
                                                :elikz,
                                                :emlif,
                                                :lblkz,
                                                :frgke,
                                                :xchar) 
                            ON DUPLICATE KEY UPDATE 
                                    loekz = values(loekz),
                                    aedat = values(aedat),
                                    matnr = values(matnr),
                                    ematn = values(ematn),
                                    txz01 = values(txz01),
                                    bukrs = values(bukrs),
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    matkl = values(matkl),
                                    ktmng = values(ktmng),
                                    menge = values(menge),
                                    meins = values(meins),
                                    uebto = values(uebto),
                                    netpr = values(netpr),
                                    peinh = values(peinh),
                                    netwr = values(netwr),
                                    brtwr = values(brtwr),
                                    pstyp = values(pstyp),
                                    knttp = values(knttp),
                                    lmein = values(lmein),
                                    bstyp = values(bstyp),
                                    bsart = values(bsart),
                                    statu = values(statu),
                                    lifnr = values(lifnr),
                                    name1 = values(name1),
                                    zterm = values(zterm),
                                    ekorg = values(ekorg),
                                    ekgrp = values(ekgrp),
                                    waers = values(waers),
                                    bedat = values(bedat),
                                    kdatb = values(kdatb),
                                    kdate = values(kdate),
                                    elikz = values(elikz),
                                    emlif = values(emlif),
                                    lblkz = values(lblkz),
                                    frgke = values(frgke),
                                    xchar = values(xchar),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->ebeln,
                                        $item->ebelp,
                                        $item->loekz,
                                        $item->aedat,
                                        $item->matnr,
                                        $item->ematn,
                                        $item->txz01,
                                        $item->bukrs,
                                        $item->werks,
                                        $item->lgort,
                                        $item->matkl,
                                        $item->ktmng,
                                        $item->menge,
                                        $item->meins,
                                        $item->uebto,
                                        $item->netpr,
                                        $item->peinh,
                                        $item->netwr,
                                        $item->brtwr,
                                        $item->pstyp,
                                        $item->knttp,
                                        $item->lmein,
                                        $item->bstyp,
                                        $item->bsart,
                                        $item->statu,
                                        $item->lifnr,
                                        $item->name1,
                                        $item->zterm,
                                        $item->ekorg,
                                        $item->ekgrp,
                                        $item->waers,
                                        $item->bedat,
                                        $item->kdatb,
                                        $item->kdate,
                                        $item->elikz,
                                        $item->emlif,
                                        $item->lblkz,
                                        $item->frgke,
                                        $item->xchar));
            }
            $conn = null;
        }
        protected function setPoSline($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->ebeln}".str_pad($item->ebelp, 5, "0", STR_PAD_LEFT).str_pad($item->etenr, 5, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zpos     ( objky, 
                                                ebeln,
                                                ebelp,
                                                etenr,
                                                eindt,
                                                slfdt,
                                                lpein,
                                                menge,
                                                ameng,
                                                wemng,
                                                wamng,
                                                estkz,
                                                dabmg,
                                                matnr,
                                                txz01,
                                                lifnr,
                                                name1,
                                                frgke)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                      values   (:objky,
                                                :ebeln,
                                                :ebelp,
                                                :etenr,
                                                :eindt,
                                                :slfdt,
                                                :lpein,
                                                :menge,
                                                :ameng,
                                                :wemng,
                                                :wamng,
                                                :estkz,
                                                :dabmg,
                                                :matnr,
                                                :txz01,
                                                :lifnr,
                                                :name1,
                                                :frgke) 
                            ON DUPLICATE KEY UPDATE 
                                    ebeln = values(ebeln),
                                    ebelp = values(ebelp),
                                    etenr = values(etenr),
                                    eindt = values(eindt),
                                    slfdt = values(slfdt),
                                    lpein = values(lpein),
                                    menge = values(menge),
                                    ameng = values(ameng),
                                    wemng = values(wemng),
                                    wamng = values(wamng),
                                    estkz = values(estkz),
                                    dabmg = values(dabmg),
                                    matnr = values(matnr),
                                    txz01 = values(txz01),
                                    lifnr = values(lifnr),
                                    name1 = values(name1),
                                    frgke = values(frgke),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(  $item->objky,
                                       $item->ebeln,
                                       $item->ebelp,
                                       $item->etenr,
                                       $item->eindt,
                                       $item->slfdt,
                                       $item->lpein,
                                       $item->menge,
                                       $item->ameng,
                                       $item->wemng,
                                       $item->wamng,
                                       $item->estkz,
                                       $item->dabmg,
                                       $item->matnr,
                                       $item->txz01,
                                       $item->lifnr,
                                       $item->name1,
                                       $item->frgke));
            }
            $conn = null;
        }
        protected function setShipment($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->tknum}";
                $sqls = "INSERT INTO zshp    (  objky,
                                                tknum,
                                                vbtyp,
                                                shtyp,
                                                tplst,
                                                ernam,
                                                erdat,
                                                erzet,
                                                vsart,
                                                vsbed,
                                                route,
                                                signi,
                                                exti1,
                                                exti2,
                                                tpbez,
                                                text1,
                                                text2,
                                                text3,
                                                text4,
                                                sttrg,
                                                tdlnr,
                                                lifnr,
                                                zzins )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :tknum,
                                                :vbtyp,
                                                :shtyp,
                                                :tplst,
                                                :ernam,
                                                :erdat,
                                                :erzet,
                                                :vsart,
                                                :vsbed,
                                                :route,
                                                :signi,
                                                :exti1,
                                                :exti2,
                                                :tpbez,
                                                :text1,
                                                :text2,
                                                :text3,
                                                :text4,
                                                :sttrg,
                                                :tdlnr,
                                                :lifnr,
                                                :zzins ) 
                            ON DUPLICATE KEY UPDATE 
                                    tknum = values(tknum),
                                    vbtyp = values(vbtyp),
                                    shtyp = values(shtyp),
                                    tplst = values(tplst),
                                    ernam = values(ernam),
                                    erdat = values(erdat),
                                    erzet = values(erzet),
                                    vsart = values(vsart),
                                    vsbed = values(vsbed),
                                    route = values(route),
                                    signi = values(signi),
                                    exti1 = values(exti1),
                                    exti2 = values(exti2),
                                    tpbez = values(tpbez),
                                    text1 = values(text1),
                                    text2 = values(text2),
                                    text3 = values(text3),
                                    text4 = values(text4),
                                    sttrg = values(sttrg),
                                    tdlnr = values(tdlnr),
                                    lifnr = values(lifnr),
                                    zzins = values(zzins),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->tknum,
                                        $item->vbtyp,
                                        $item->shtyp,
                                        $item->tplst,
                                        $item->ernam,
                                        $item->erdat,
                                        $item->erzet,
                                        $item->vsart,
                                        $item->vsbed,
                                        $item->route,
                                        $item->signi,
                                        $item->exti1,
                                        $item->exti2,
                                        $item->tpbez,
                                        $item->text1,
                                        $item->text2,
                                        $item->text3,
                                        $item->text4,
                                        $item->sttrg,
                                        $item->tdlnr,
                                        $item->lifnr,
                                        $item->zzins));
            }
            $conn = null;
        }
        protected function setDelivery($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->vbeln}".str_pad($item->posnr, 6, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zibd    (  objky,
                                                vbeln,
                                                posnr,
                                                ernam,
                                                erdat,
                                                erzet,
                                                vstel,
                                                lfart,
                                                ablad,
                                                route,
                                                lifsk,
                                                vbtyp,
                                                lifnr,
                                                kunnr,
                                                kunag,
                                                brgew,
                                                ntgew,
                                                gewei,
                                                anzpk,
                                                pstyv,
                                                matnr,
                                                arktx,
                                                werks,
                                                lgort,
                                                charg,
                                                lfimg,
                                                meins,
                                                vrkme,
                                                vbelv,
                                                posnv,
                                                vgbel,
                                                vgpos)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :vbeln,
                                                :posnr,
                                                :ernam,
                                                :erdat,
                                                :erzet,
                                                :vstel,
                                                :lfart,
                                                :ablad,
                                                :route,
                                                :lifsk,
                                                :vbtyp,
                                                :lifnr,
                                                :kunnr,
                                                :kunag,
                                                :brgew,
                                                :ntgew,
                                                :gewei,
                                                :anzpk,
                                                :pstyv,
                                                :matnr,
                                                :arktx,
                                                :werks,
                                                :lgort,
                                                :charg,
                                                :lfimg,
                                                :meins,
                                                :vrkme,
                                                :vbelv,
                                                :posnv,
                                                :vgbel,
                                                :vgpos) 
                            ON DUPLICATE KEY UPDATE 
                                    objky = values(objky),
                                    vbeln = values(vbeln),
                                    posnr = values(posnr),
                                    ernam = values(ernam),
                                    erdat = values(erdat),
                                    erzet = values(erzet),
                                    vstel = values(vstel),
                                    lfart = values(lfart),
                                    ablad = values(ablad),
                                    route = values(route),
                                    lifsk = values(lifsk),
                                    vbtyp = values(vbtyp),
                                    lifnr = values(lifnr),
                                    kunnr = values(kunnr),
                                    kunag = values(kunag),
                                    brgew = values(brgew),
                                    ntgew = values(ntgew),
                                    gewei = values(gewei),
                                    anzpk = values(anzpk),
                                    pstyv = values(pstyv),
                                    matnr = values(matnr),
                                    arktx = values(arktx),
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    charg = values(charg),
                                    lfimg = values(lfimg),
                                    meins = values(meins),
                                    vrkme = values(vrkme),
                                    vbelv = values(vbelv),
                                    posnv = values(posnv),
                                    vgbel = values(vgbel),
                                    vgpos = values(vgpos),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->vbeln,
                                        $item->posnr,
                                        $item->ernam,
                                        $item->erdat,
                                        $item->erzet,
                                        $item->vstel,
                                        $item->lfart,
                                        $item->ablad,
                                        $item->route,
                                        $item->lifsk,
                                        $item->vbtyp,
                                        $item->lifnr,
                                        $item->kunnr,
                                        $item->kunag,
                                        $item->brgew,
                                        $item->ntgew,
                                        $item->gewei,
                                        $item->anzpk,
                                        $item->pstyv,
                                        $item->matnr,
                                        $item->arktx,
                                        $item->werks,
                                        $item->lgort,
                                        $item->charg,
                                        $item->lfimg,
                                        $item->meins,
                                        $item->vrkme,
                                        $item->vbelv,
                                        $item->posnv,
                                        $item->vgbel,
                                        $item->vgpos ));
            }
            $conn = null;
        }
        protected function setGoodsMvt($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->mblnr}".str_pad($item->mjahr, 4, "0", STR_PAD_LEFT).str_pad($item->zeile, 4, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zmvt    (  objky,
                                                mblnr, 
                                                mjahr,
                                                zeile,
                                                bwart,
                                                matnr,
                                                txz01,
                                                werks,
                                                lgort,
                                                charg,
                                                insmk,
                                                sobkz,
                                                lifnr,
                                                name1,
                                                kunnr,
                                                waers,
                                                bnbtr,
                                                menge,
                                                meins,
                                                lsmng,
                                                lsmeh,
                                                ebeln,
                                                ebelp,
                                                lfbja,
                                                lfbnr,
                                                sjahr,
                                                smbln,
                                                bukrs,
                                                belnr,
                                                buzei,
                                                buzum,
                                                rspos,
                                                vgart,
                                                blart,
                                                budat,
                                                cpudt,
                                                cputm,
                                                xblnr,
                                                bktxt,
                                                xabln,
                                                shkzg)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :mblnr, 
                                                :mjahr,
                                                :zeile,
                                                :bwart,
                                                :matnr,
                                                :txz01,
                                                :werks,
                                                :lgort,
                                                :charg,
                                                :insmk,
                                                :sobkz,
                                                :lifnr,
                                                :name1,
                                                :kunnr,
                                                :waers,
                                                :bnbtr,
                                                :menge,
                                                :meins,
                                                :lsmng,
                                                :lsmeh,
                                                :ebeln,
                                                :ebelp,
                                                :lfbja,
                                                :lfbnr,
                                                :sjahr,
                                                :smbln,
                                                :bukrs,
                                                :belnr,
                                                :buzei,
                                                :buzum,
                                                :rspos,
                                                :vgart,
                                                :blart,
                                                :budat,
                                                :cpudt,
                                                :cputm,
                                                :xblnr,
                                                :bktxt,
                                                :xabln,
                                                :shkzg) 
                            ON DUPLICATE KEY UPDATE 
                                    mblnr = values(mblnr), 
                                    mjahr = values(mjahr),
                                    zeile = values(zeile),
                                    bwart = values(bwart),
                                    matnr = values(matnr),
                                    txz01 = values(txz01),
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    charg = values(charg),
                                    insmk = values(insmk),
                                    sobkz = values(sobkz),
                                    lifnr = values(lifnr),
                                    name1 = values(name1),
                                    kunnr = values(kunnr),
                                    waers = values(waers),
                                    bnbtr = values(bnbtr),
                                    menge = values(menge),
                                    meins = values(meins),
                                    lsmng = values(lsmng),
                                    lsmeh = values(lsmeh),
                                    ebeln = values(ebeln),
                                    ebelp = values(ebelp),
                                    lfbja = values(lfbja),
                                    lfbnr = values(lfbnr),
                                    sjahr = values(sjahr),
                                    smbln = values(smbln),
                                    bukrs = values(bukrs),
                                    belnr = values(belnr),
                                    buzei = values(buzei),
                                    buzum = values(buzum),
                                    rspos = values(rspos),
                                    vgart = values(vgart),
                                    blart = values(blart),
                                    budat = values(budat),
                                    cpudt = values(cpudt),
                                    cputm = values(cputm),
                                    xblnr = values(xblnr),
                                    bktxt = values(bktxt),
                                    xabln = values(xabln),
                                    shkzg = values(shkzg),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->mblnr, 
                                        $item->mjahr,
                                        $item->zeile,
                                        $item->bwart,
                                        $item->matnr,
                                        $item->txz01,
                                        $item->werks,
                                        $item->lgort,
                                        $item->charg,
                                        $item->insmk,
                                        $item->sobkz,
                                        $item->lifnr,
                                        $item->name1,
                                        $item->kunnr,
                                        $item->waers,
                                        $item->bnbtr,
                                        $item->menge,
                                        $item->meins,
                                        $item->lsmng,
                                        $item->lsmeh,
                                        $item->ebeln,
                                        $item->ebelp,
                                        $item->lfbja,
                                        $item->lfbnr,
                                        $item->sjahr,
                                        $item->smbln,
                                        $item->bukrs,
                                        $item->belnr,
                                        $item->buzei,
                                        $item->buzum,
                                        $item->rspos,
                                        $item->vgart,
                                        $item->blart,
                                        $item->budat,
                                        $item->cpudt,
                                        $item->cputm,
                                        $item->xblnr,
                                        $item->bktxt,
                                        $item->xabln,
                                        $item->shkzg));
            }
            $conn = null;
        }
        protected function setInvoice($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->bukrs}{$item->belnr}".str_pad($item->gjahr, 4, "0", STR_PAD_LEFT).str_pad($item->buzei, 4, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zinv    (  objky,
                                                bukrs,
                                                belnr,
                                                gjahr,
                                                buzei,
                                                lifnr,
                                                name1,
                                                xblnr,
                                                bldat,
                                                budat,
                                                ebeln,
                                                ebelp,
                                                lfbnr,
                                                lfgja,
                                                wrbtr )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :bukrs,
                                                :belnr,
                                                :gjahr,
                                                :buzei,
                                                :lifnr,
                                                :name1,
                                                :xblnr,
                                                :bldat,
                                                :budat,
                                                :ebeln,
                                                :ebelp,
                                                :lfbnr,
                                                :lfgja,
                                                :wrbtr ) 
                            ON DUPLICATE KEY UPDATE 
                                bukrs = values(bukrs),
                                belnr = values(belnr),
                                gjahr = values(gjahr),
                                buzei = values(buzei),
                                lifnr = values(lifnr),
                                name1 = values(name1),
                                xblnr = values(xblnr),
                                bldat = values(bldat),
                                budat = values(budat),
                                ebeln = values(ebeln),
                                ebelp = values(ebelp),
                                lfbnr = values(lfbnr),
                                lfgja = values(lfgja),
                                wrbtr = values(wrbtr), 
                                cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->bukrs,
                                        $item->belnr,
                                        $item->gjahr,
                                        $item->buzei,
                                        $item->lifnr,
                                        $item->name1,
                                        $item->xblnr,
                                        $item->bldat,
                                        $item->budat,
                                        $item->ebeln,
                                        $item->ebelp,
                                        $item->lfbnr,
                                        $item->lfgja,
                                        $item->wrbtr ));
            }
            $conn = null;
        }
        protected function setSubstock($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->matnr}{$item->werks}{$item->charg}{$item->sobkz}{$item->lifnr}";
                $sqls = "INSERT INTO zsub    (  objky,
                                                matnr, 
                                                werks,
                                                charg,
                                                sobkz,
                                                lifnr,
                                                name1,
                                                txz01,
                                                lfgja,
                                                lfmon,
                                                lbspr,
                                                lblab,
                                                lbins)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :matnr, 
                                                :werks,
                                                :charg,
                                                :sobkz,
                                                :lifnr,
                                                :name1,
                                                :txz01,
                                                :lfgja,
                                                :lfmon,
                                                :lbspr,
                                                :lblab,
                                                :lbins) 
                            ON DUPLICATE KEY UPDATE 
                                matnr = values(matnr), 
                                werks = values(werks),
                                charg = values(charg),
                                sobkz = values(sobkz),
                                lifnr = values(lifnr),
                                name1 = values(name1),
                                txz01 = values(txz01),
                                lfgja = values(lfgja),
                                lfmon = values(lfmon),
                                lbspr = values(lbspr),
                                lblab = values(lblab),
                                lbins = values(lbins),
                                cngdt = NOW()";
                $stmt = $conn->prepare($sqls);
                $stmt->execute(array($item->objky,   
                                     $item->matnr, 
                                     $item->werks,
                                     $item->charg,
                                     $item->sobkz,
                                     $item->lifnr,
                                     $item->name1,
                                     $item->txz01,
                                     $item->lfgja,
                                     $item->lfmon,
                                     $item->lbspr,
                                     $item->lblab,
                                     $item->lbins));
            }
            $conn = null;
        }
        
        protected function setPlant($rqst) {
            $conn = $this->connect();
            
            foreach($rqst->items as $item) {
                $item->objky = "{$item->werks}";
                $sqls = "INSERT INTO plants (   objky,
                                                objnm, 
                                                werks )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :objnm, 
                                                :werks) 
                            ON DUPLICATE KEY UPDATE 
                                objnm = values(objnm), 
                                werks = values(werks),
                                cngdt = NOW()";
                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->werks,   
                                        $item->name1, 
                                        $item->werks));
            }
            $conn = null;
        }
        protected function setStrLoc($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->werks}{$item->lgort}";
                $sqls = "INSERT INTO stor_loc ( objky,
                                                objnm, 
                                                werks,
                                                lgort,
                                                cngdt )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                    values  (   :objky,
                                                :objnm, 
                                                :werks,
                                                :lgort,
                                                NOW()) 
                        ON DUPLICATE KEY UPDATE 
                                    objnm = values(objnm), 
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    cngdt = NOW()";
                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,   
                                        $item->lgobe, 
                                        $item->werks,
                                        $item->lgort));
            }
            $conn = null;
            
        }
        protected function setMatLoc($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->matnr}{$item->werks}{$item->lgort}";
                $sqls = "INSERT INTO zmlc     ( objky,
                                                objnm,
                                                matnr, 
                                                werks,
                                                lgort,
                                                labst,
                                                cngdt )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                    values  (   :objky,
                                                :objnm,
                                                :matnr, 
                                                :werks,
                                                :lgort,
                                                :labst,
                                                NOW()) 
                        ON DUPLICATE KEY UPDATE 
                                    objnm = values(objnm), 
                                    matnr = values(matnr),
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    labst = values(labst),
                                    cngdt = NOW()";
                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,   
                                        $item->lgobe,
                                        $item->matnr, 
                                        $item->werks,
                                        $item->lgort,
                                        $item->labst));
            }
            $conn = null;
            
        }
        protected function modVehPass($rqst) {
            $conn = new Conn();
            foreach($rqst->items as $pass) {
                foreach($pass->items as $item) {
                    $this->setPoSline($item);
                }
                $query = "update veh_pass 
                             set zvpno   = :zvpno,
                                 tknum   = :tknum,
                                 ztokn   = :ztokn
                           where pass_id = :pass_id";
                $param = array( $pass->vpass->zvpno,
                                $pass->vpass->tknum,
                                $pass->vpass->ztokn,
                                $pass->vpass->zpsid );
                $conn->execQuery($query,$param);
                foreach($pass->chlns as $chln) {
                    foreach($chln->items as $item) {
                        $query = "update veh_item 
                                    set vgbel = :vgbel,
                                        vgpos = :vgpos,
                                        md103 = :md103,
                                        my103 = :my103,
                                        mi103 = :mi103,
                                        md104 = :md104,
                                        my104 = :my104,
                                        mi104 = :mi104,
                                        md124 = :md124,
                                        my124 = :my124,
                                        mi124 = :mi124,
                                        brgew = :brgew,
                                        ztgew = :ztgew,
                                        ntgew = :ntgew,
                                        md105 = :md105,
                                        my105 = :my105,
                                        mi105 = :mi105
                                where pass_id = :pass_id
                                    and chln_id = :chln_id
                                    and item_id = :item_id";
                        $param = array( $item->vgbel,
                                        $item->vgpos,
                                        $item->md103,
                                        $item->my103,
                                        $item->mi103,
                                        $item->md104,
                                        $item->my104,
                                        $item->mi104,
                                        $item->md124,
                                        $item->my124,
                                        $item->mi124,
                                        $item->brgew,
                                        $item->ztgew,
                                        $item->ntgew,
                                        $item->md105,
                                        $item->my105,
                                        $item->mi105,
                                        $item->zpsid,
                                        $item->zchid,
                                        $item->zitem);
                        $conn->execQuery($query,$param);
                        
                    }
                }  
            }
            $conn = null;
        }
        protected function modVPStatus($rqst) {
            $cntr = new \Contr\VehPassContr();
            foreach($rqst->items as $vpas) {
                $pass = $vpas->vpass;
                $rqst->pass_id = $pass->zpsid;
                $cntr->updtVPStatus($rqst);
            }
            
        }

    }
    